function radialGraph(){var a=this;a.init=function(b){if(b!=void 0)a.element=b,a.canvas=void 0,a.data=void 0,a.numdata=void 0,a.settings={resource:a.element.attributes["pachube-resource"].value,api_key:a.element.attributes["pachube-key"].value,FaceColor:"grey",LineColor:"black",InnerColor:"white",OuterColor:"white",BackgroundColor:"#fff",TimeSpan:"24 hours",ShowClock:!0,Font:a.element.style.font||"9pt Arial"},a.parse_pachube_options(a.element.attributes["pachube-options"].value),a.clocktime=a.settings.TimeSpan==
"24 hours",graphId="radgraph"+Math.floor(Math.random()*1E5),a.element.innerHTML='<canvas id="'+graphId+'"></canvas>',a.c=document.getElementById(graphId),a.b=document.body,a.a=a.c.getContext("2d"),a.width=a.c.width=parseInt(a.element.style.width)||100,a.height=a.c.height=parseInt(a.element.style.height)||100,a.centerX=a.width/2,a.centerY=a.height/2,a.radius=a.width/2.2,a.msg="( synchronizing )",a.data=void 0,a.updatePachube(),a.draw(),(a.settings.ShowClock||a.numdata==void 0)&&setInterval(a.draw,
1E3)};a.draw=function(){a.a.clearRect(0,0,a.width,a.height);a.a.restore();a.plotClockFace();a.settings.ShowClock&&a.plotClockHands();a.plotDataPoints()};a.updateData=function(){a.gradient1=a.a.createRadialGradient(0,0,0,0,0,a.radius);a.gradient1.addColorStop(0,a.hex2rgb(a.settings.InnerColor,1));a.gradient1.addColorStop(1,a.hex2rgb(a.settings.OuterColor,0.5));a.gradient2=a.a.createRadialGradient(0,0,0,0,0,a.radius);a.gradient2.addColorStop(0,a.hex2rgb(a.settings.InnerColor,0.5));a.gradient2.addColorStop(1,
a.hex2rgb(a.settings.OuterColor,0.6));a.numdata=[];a.datedata=[];min=9999999999;for(var b=max=0;b<a.data.length;b+=1){var c=parseFloat(a.data[b].value);max=max<c?c:max;min=min>c?c:min;a.numdata.push(c);c=a.data[b].at;c.indexOf(".")>0&&(c=c.substring(0,c.indexOf(".")));a.datedata.push(new Date(c))}a.scale=a.radius/(max-min);a.min=min;a.max=max};a.plotDataPoints=function(){if(a.data!=void 0)a.numdata==void 0&&a.updateData(),a.a.save(),a.a.translate(a.centerX,a.centerY),a.a.fillStyle=a.gradient1,a.a.strokeStyle=
a.settings.LineColor,a.a.lineWidth=1,a.a.beginPath(),a.plotDataRange(0,Math.floor(a.numdata.length/2)),a.a.fill(),a.a.beginPath(),a.a.fillStyle=a.gradient2,a.plotDataRange(Math.ceil(a.numdata.length/2),a.numdata.length),a.a.stroke(),a.a.fill(),a.a.restore()};a.plotDataRange=function(b,c){for(var e=!1,f=null,g=b;g<c;g++)amount=(a.numdata[g]-a.min)*a.scale,a.clocktime=!0,a.clocktime?(d=a.datedata[g],dH=d.getHours()+d.getMinutes()/60+d.getSeconds()/3600,delta=dH/12):(d=new Date,dH=d.getHours()+d.getMinutes()/
60+d.getSeconds()/3600,delta=dH/12+g/a.numdata.length),dx1=amount*Math.sin(6.28*delta),dy1=amount*-Math.cos(6.28*delta),e?a.a.lineTo(dx1,dy1):(f=[dx1,dy1],e=!0,a.a.moveTo(dx1,dy1));e&&a.a.lineTo(f[0],f[1])};a.plotClockFace=function(){a.a.save();a.a.translate(a.centerX,a.centerY);a.a.strokeStyle=a.settings.FaceColor;a.a.fillStyle=a.settings.BackgroundColor;a.a.lineWidth=3;a.a.beginPath();a.a.arc(0,0,a.radius,0,Math.PI*2,!1);a.a.stroke();a.a.fill();a.a.font=a.settings.Font;a.a.fillStyle=a.settings.FaceColor;
a.a.fillText(a.msg,-a.msg.length*3,-a.radius-8);a.a.restore()};a.plotClockHands=function(){a.a.save();a.a.translate(a.centerX,a.centerY);a.a.strokeStyle="rgba(0,0,0,0.3)";a.a.lineWidth=a.radius/10;d=new Date;dS=d.getSeconds()/60;dM=(d.getMinutes()+dS)/60;dH=(d.getHours()+dM)/12;pi2=Math.PI*2;a.a.beginPath();a.a.moveTo(0,0);dx1=0.9*a.radius*Math.sin(pi2*dH);dy1=0.9*a.radius*-Math.cos(pi2*dH);a.a.lineTo(dx1,dy1);a.a.stroke();a.a.beginPath();a.a.moveTo(0,0);dx1=a.radius*Math.sin(pi2*dM);dy1=a.radius*
-Math.cos(pi2*dM);a.a.lineTo(dx1,dy1);a.a.stroke();a.a.beginPath();a.a.arc(0,0,a.radius*0.95,-pi2/4,pi2*(dS==0?1:dS)-pi2/4,!1);a.a.stroke();a.a.restore()};a.parse_pachube_options=function(b){b==void 0&&(b="");options_hash=[];for(re=/([^:]*):([^;]*);/;match=b.match(re);)b=b.replace(re,""),options_hash[match[1].trim()]=match[2].trim();a.settings.FaceColor=options_hash["text-color"]||"#555555";a.settings.LineColor=options_hash["line-color"]||"#0000ff";a.settings.InnerColor=options_hash["grid-color"]||
"#03030b";a.settings.OuterColor=options_hash["border-color"]||"#a000ff";a.settings.BackgroundColor=options_hash["background-color"]||"#ffffff";a.settings.TimeSpan=options_hash.timespan||"24 hours";a.settings.ShowClock=options_hash.showclock!="no"};a.set_interval=function(b){switch(b){case "3 months":return a.settings.Interval=5184E3,"3month";case "4 days":return a.settings.Interval=36E4,"4day";case "last hour":return a.settings.Interval=3E4,"1hour";default:case "24 hours":return a.settings.Interval=
12E4,a.settings.TimeSpan="24 hours","24hour"}};a.updatePachube=function(){var b=a.set_interval(a.settings.TimeSpan);typeof console!="undefined"&&console.log("Updating Pachube data: "+a.settings.resource+" - next in "+a.settings.Interval/1E3+"s");a.settings.Interval>0&&setTimeout(a.updatePachube,a.settings.Interval);jQuery.getJSON("https://api.pachube.com/v2/"+a.settings.resource+".json?duration="+b+"&key="+a.settings.api_key,function(b){a.numdata=void 0;a.data=b.datapoints;a.msg=a.settings.TimeSpan})};
a.hex2rgb=function(a,c){for(var e=a.replace("#","").match(/(.{2})/g),f=3;f--;)e[f]=parseInt(e[f],16);if(typeof c=="undefined")return"rgb("+e.join(", ")+")";return"rgba("+e.join(", ")+", "+c+")"}}
if(typeof jQuery==="undefined"){var script_tag=document.createElement("script");script_tag.setAttribute("type","text/javascript");script_tag.setAttribute("src","http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js");script_tag.onload=startRadialGraph;script_tag.onreadystatechange=function(){(this.readyState=="complete"||this.readyState=="loaded")&&startRadialGraph(!1)};document.getElementsByTagName("head")[0].appendChild(script_tag)}else startRadialGraph(!0);
function startRadialGraph(){jQuery(document).ready(function(a){a(".pachube-radial").each(function(){a(this).hasClass("p-r-init")||(a(this).addClass("p-r-init"),(new radialGraph).init(this))})})};
